-- =========================================================
-- FarmTablet v2 – MarketDynamicsApp  (stub)
-- The Market Dynamics drawer is registered in IncomeApp.lua
-- alongside the other companion-mod integration apps.
-- This file exists as a named placeholder so the source()
-- ordering in main.lua remains self-documenting.
-- =========================================================
