-- =========================================================
-- FarmTablet v2 – SeasonalCropStressApp  (stub)
-- The Seasonal Crop Stress drawer is registered in
-- IncomeApp.lua alongside the other companion-mod apps.
-- This file exists as a named placeholder so the source()
-- ordering in main.lua remains self-documenting.
-- =========================================================
