-- =========================================================
-- FarmTablet v2 – SoilFertilizerApp  (stub)
-- The Soil Fertilizer drawer is registered in IncomeApp.lua
-- alongside the other companion-mod integration apps.
-- This file exists as a named placeholder so the source()
-- ordering in main.lua remains self-documenting.
-- =========================================================
